name: Deploy to Firebase Functions
"on":
  push:
    branches:
      - master
env:
  CI: false

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download deps
        working-directory: functions
        run: npm install

      - name: Deploy
        run: npx firebase-tools deploy --project default
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}